query questions {
  faqCategories {
    data {
      id
      arTitle
      faq {
        id
        arQuestion
        arAnswer
        enAnswer
        enQuestion
      }
    }
  }
}

mutation createfaq(
  $arq: String!
  $ara: String!
  $enq: String!
  $ena: String!
  $cid: String!
) {
  createFaqBoard(
    input: {
      arQuestion: $arq
      arAnswer: $ara
      enQuestion: $enq
      enAnswer: $ena
      categoryId: $cid
    }
  ) {
    data {
      arQuestion
      arAnswer
    }
  }
}

mutation updatefaq(
  $arq: String!
  $ara: String!
  $enq: String!
  $ena: String!
  $cid: String!
  $faqid: ID!
) {
  updateFaqBoard(
    input: {
      arQuestion: $arq
      arAnswer: $ara
      enQuestion: $enq
      enAnswer: $ena
      categoryId: $cid
      faqId: $faqid
    }
  ) {
    data {
      id
      arQuestion
      arAnswer
    }
    success
  }
}

mutation deletefaq($faqid: String!) {
  deleteFaqBoard(input: { faqId: $faqid }) {
    success
  }
}
