mutation login($email: String!, $password: String!) {
  emailAndPasswordLoginBoard(
    input: { email: $email, password: $password, device: DESKTOP }
  ) {
    message
    data {
      token
    }
  }
}

