query getUser {
  consultantRequestsBoard {
    data {
      items {
        user {
          age
          email
          enFirstName
          enFullName
          enLastName
          gender
          profilePicture
          phone
          role
        }
      }
    }
  }
}
